### ISSUE TITLE
Duplicated Collection creation in commit 

### ISSUE THREAD

**Issue by israeldboliveira** [openmarketplace/openmarketplace#42]
On this commit [Working on architecture and basis.](https://github.com/openmarketplace/openmarketplace/commit/442f8b1b6d1a39a2d92a2c8374284327e35e5d88)

The same collection is created in to files:  Collection "catalogs"

[imports/api/catalogs/catalog-model.js](https://github.com/openmarketplace/openmarketplace/commit/442f8b1b6d1a39a2d92a2c8374284327e35e5d88#diff-e54ad5bee6eb39d388028e64d52b8bf2)

[imports/api/conversations/conversations-model.js](https://github.com/openmarketplace/openmarketplace/commit/442f8b1b6d1a39a2d92a2c8374284327e35e5d88#diff-126491d185b8e45191658fcb7176a114)

@lindoelio :  Is this code correct?

**Comment by lindoelio** [comment]
@israeldboliveira It work is in progress... I will continue the makes for this yet. Don't worry.
